services:
  nats:
    image: nats:latest
    container_name: nats
    ports:
      - "4222:4222"
      - "8222:8222" # Monitoring UI
    restart: always

  feed-service:
    build:
      context: ./pajarit-feed-service
    container_name: feed-service
    ports:
      - "8080:8080"
    environment:
      - CONFIG_PATH=/config/config.yaml
    volumes:
      - ./config/feed-config.yaml:/config/config.yaml:ro
      - ./data/pajarit.db:/app/data/pajarit.db
    depends_on:
      - nats

  timeline-worker:
    build:
      context: ./pajarit-timeline-worker
    container_name: timeline-worker
    ports:
      - "8081:8081"
    environment:
      - CONFIG_PATH=/config/config.yaml
    volumes:
      - ./config/worker-config.yaml:/config/config.yaml:ro
      - ./data/pajarit.db:/app/data/pajarit.db
    depends_on:
      - nats
